AdaptDichoticInterruptions(...
    'Interrupted speech with a buzzy distractor, both alternating between the ears', ...
    'NoiseFile', 'Fbabble1-Fx.wav', 'SNR', 0, 'Ear', 'A', 'MaxTrials', 22, 'Listener', 'L27b', 'ListNumber', 10.0 )
